### ISSUE TITLE
how to remove media notification on notification panel

### ISSUE THREAD

**Issue by Wizpna** [siddhesh-tamhanekar/media_player#2]
Please, I want to remove media notification from my notification panel but it does not work unless I restart my phone then the media notification will be removed.

Can you add something like a close button, so that when a user clicks on the button the media player will close and disappear from the notification panel.

**Comment by hulastone** [comment]
@Wizpna : maybe help you. this below code to start player. if you want to hide notification, 
You set property "showNotification = false". I haven't tested yet, only thinking ^_^

void initState() {
    // first argument for isBackground next for showNotification.
    player = MediaPlayerPlugin.create(isBackground: true, showNotification: true);
    initVideo();
    super.initState();
  }

**Comment by siddhesh-tamhanekar** [comment]
@hulastone  it's not like that showNotificaition is the setting which toggles the visibility of the Persistent player notification.

The @Wizpna  is asking about the feature for a closing player from the notification panel.

@Wizpna  You don't have to restart the phone when an app is closed the notification automatically get closed.

The feature is in line and it will available soon.
Thanks for your vote for the feature.

**Comment by siddhesh-tamhanekar** [comment]
@Wizpna  The bug of the not closing media player on some devices has been fixed in version 0.0.6 so closing this request
yes. there could be a close button to close the player manually when the user wants to but it's another enhancement rather than a bug.
