### ISSUE TITLE
On running the example

### ISSUE THREAD

**Issue by hiteshjoshi** [siddhesh-tamhanekar/media_player#9]
https://askparrot.com/media/1/stream/
Works fine on IOS

I/DpmTcmClient(10870): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
E/ExoPlayerImplInternal(10870): Source error.
E/ExoPlayerImplInternal(10870): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(10870):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
E/ExoPlayerImplInternal(10870):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
E/ExoPlayerImplInternal(10870):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(10870):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10870):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10870):         at java.lang.Thread.run(Thread.java:764)

**Comment by siddhesh-tamhanekar** [comment]
Hi @hiteshjoshi I have tested the above URL with different HLS stream tester sites they were also unable to play the URL. 
Please check the https://exoplayer.dev/supported-formats.html for supported format.
